### ISSUE TITLE
Reference guide improvements

### ISSUE THREAD

**Issue by chris-askbrian** [northdata/api#9]
Hi,
I just experienced a undocumented behavior in your reference guide while trying out your rest api that lead to a bit confusion in our team. 

It looks like that the `/company/v1/publications` endpoint is not behaving as documented (at least if you are only using the reference guide), while not providing a "source" parameter which is said to be "required" you still can query this endpoint which results in publication results from "Hrb" sources. If a field is marked as "required" I (and at least the other developers in our team) expected an error for an missing required parameter not defaulting to one (without documentation).
Please provide an error message or adjust your reference guide (e.g. set the parameter in the reference guide to optional and mention the defaulting to "Hrb" source behavior) 

EDIT: I just saw that you mentioned this behavior on the github readme of this repository but still... wouldn't the reference guide be the better place to mention this behavior? (+ the fact that its actually not a required field)

**Comment by reezom** [comment]
cc @kytaihora

**Comment by reezom** [comment]
@chris-askbrian thanks for reporting!
We'll update the `yaml` file that is the basis for the reference guide. In hindsight, it would have been better not to have a default here, but this can't be changed because some users may already rely on it.

**Comment by chris-askbrian** [comment]
As long as it is documented we can work with it ;)

**Comment by reezom** [comment]
We decided that it is better to document this parameter as "required". Of course, it would be better to have an error message if it is omitted, but for legacy reason this is not the case.
